# The theme configuration variable is not needed since the theme is installed
# using Hugo Modules. If the theme changes revisit this.
# theme = "congo"

baseURL = "https://website.matthew-sanabria.workers.dev"
defaultContentLanguage = "en"
enableRobotsTXT = true
summaryLength = 0
timeout = "120s"

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]
